### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by jrjsmrtn** [pycompiled/compiled#2]
https://github.com/pycompiled/compiled/blob/38b7b340a7f7549a446b858988c695e48f654795/build.py#L80

Don't you miss a comma between "-m" and "unitest" ?

**Comment by tusharsadhwani** [comment]
It does look weird, but the concatenated `"-munittest"` is indeed valid in Python. It was intentional, but I can see why it would confuse people.

PR to add the comma is welcome.

**Comment by jrjsmrtn** [comment]
Yes, I was just wondering if it was intentional as in the next line they were comma-separated. PR is submitted.
Very interesting work, btw :-)

**Comment by tusharsadhwani** [comment]
Thanks!
